project_id = "qdsjmhafojbmqcwlkmra"

[functions.ai-chat]
verify_jwt = false

[functions.download-digital-product]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.cart-recovery]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false