// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public keys — safe to hardcode in frontend (security enforced by Supabase RLS policies).
// These are fallbacks for when VITE_ env vars are not available (e.g. Vercel build with gitignored .env).
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  'https://ebormxtkzertyxgszbip.supabase.co';

const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVib3JteHRremVydHl4Z3N6YmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1OTQwMzUsImV4cCI6MjA4OTE3MDAzNX0.IPm_mpEfutyLrQ6FmuooqWH3MbXA7s4uv8sqfTtaWdY';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    flowType: 'pkce',
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
